services:

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432


  ques-lavka-web-api:
    container_name: ques-lavka-web-api
    build:
      context: ./
      dockerfile: web-api.Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - "8003:8000"
    depends_on:
      - pg
    env_file:
      - .env
    logging:
      options:
        max-size: 200m
